#BSUB -J three_incon_subtype[1]
#BSUB -W 15:00
#BSUB -o /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/three_incon_subtypel_log%I.out
#BSUB -e /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/three_incon_subtype_%I.err
#BSUB –cwd /rsrch8/home/epi/ychang11/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u ychang11@mdanderson.org
#BSUB -n 1
#BSUB -M 32
#BSUB -R rusage[mem=32]

# run 1-3
module load R/4.4.1
Rscript /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/three_incon_adeno_scc.R $LSB_JOBINDEX 1 >/rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/three_incon_adeno_scc_$LSB_JOBINDEX.out
