#BSUB -J two_incon_overall[1-3]
#BSUB -W 15:00
#BSUB -o /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/two_incon_overall_log%I.out
#BSUB -e /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/two_incon_overall_%I.err
#BSUB –cwd /rsrch8/home/epi/ychang11/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u ychang11@mdanderson.org
#BSUB -n 1
#BSUB -M 32
#BSUB -R rusage[mem=32]

# run 1-3
module load R/4.4.1
Rscript /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/two_incon_overall.R $LSB_JOBINDEX 1 >/rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/two_incon_overall_$LSB_JOBINDEX.out
