#BSUB -J ukbanalysis[4]
#BSUB -W 4:00
#BSUB -o /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/analyze_rep_log%I.out
#BSUB -e /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/analyze_rep_%I.err
#BSUB –cwd /rsrch8/home/epi/ychang11/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u ychang11@mdanderson.org
#BSUB -n 1
#BSUB -M 64
#BSUB -R rusage[mem=64]

# run 4
module load R/4.3.1
Rscript /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/replication_lung.R $LSB_JOBINDEX 1 >/rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/analyze_rep_$LSB_JOBINDEX.out
