#BSUB -J replication_sim[21-22]
#BSUB -W 8:00
#BSUB -o /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_rep_log%I.out
#BSUB -e /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_rep_%I.err
#BSUB –cwd /rsrch8/home/epi/ychang11/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u ychang11@mdanderson.org
#BSUB -n 1
#BSUB -M 64
#BSUB -R rusage[mem=64]

# run 100 simulations
module load R/4.3.1
Rscript /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/replication_simulation.R $LSB_JOBINDEX 1 >/rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_rep_$LSB_JOBINDEX.out
