#BSUB -J sim_three[1-1500]
#BSUB -W 24:00
#BSUB -o /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_three_all_log%I.out
#BSUB -e /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_three_all_%I.err
#BSUB –cwd /rsrch8/home/epi/ychang11/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u ychang11@mdanderson.org
#BSUB -n 1
#BSUB -M 32
#BSUB -R rusage[mem=32]

# Decode aID (1-100) and Snum (1-15) from flat job index (1-1500)
SNUM=$(( (LSB_JOBINDEX - 1) / 100 + 1 ))
AID=$(( (LSB_JOBINDEX - 1) % 100 + 1 ))

module load R/4.4.1
Rscript /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/sim_three_revised.R \
    $AID $SNUM \
    > /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_three_s${SNUM}_${AID}.out