#BSUB -J sim_three_s5[1-100]
#BSUB -W 10:00
#BSUB -o /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_three_s5_log%I.out
#BSUB -e /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_three_s5_%I.err
#BSUB –cwd /rsrch8/home/epi/ychang11/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u ychang11@mdanderson.org
#BSUB -n 1
#BSUB -M 64
#BSUB -R rusage[mem=64]

# run 100 simulations
module load R/4.3.1
Rscript /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/sim_three.R $LSB_JOBINDEX 5 >/rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/sim_three_s5_$LSB_JOBINDEX.out
