#BSUB -J PRS_revised_two[1]
#BSUB -W 15:00
#BSUB -o /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/PRS_revised_two_%I.out
#BSUB -e /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/PRS_revised_two_%I.err
#BSUB –cwd /rsrch8/home/epi/ychang11/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u ychang11@mdanderson.org
#BSUB -n 1
#BSUB -M 20
#BSUB -R rusage[mem=20]


module load R/4.4.1
Rscript /rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/PRS_revised_two.R $LSB_JOBINDEX 1 >/rsrch8/home/epi/ychang11/csmGmm_reproduce/Lung/errDir/PRS_revised_two_$LSB_JOBINDEX.out
